
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("6d2ad470-c11a-418a-b73e-442bc0c8cd74")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("dashbaordDBModel", "FK_Reports_Module1", "Module", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType([Module]), "Reports", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Report), True)>
<Assembly: EdmRelationshipAttribute("dashbaordDBModel", "FK_ReportLogStatus_Reports", "Reports", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Report), "ReportLogStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ReportLogStatu), True)>
<Assembly: EdmRelationshipAttribute("dashbaordDBModel", "FK_ReportLogStatus_ReportStatus", "ReportStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(ReportStatu), "ReportLogStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ReportLogStatu), True)>
<Assembly: EdmRelationshipAttribute("dashbaordDBModel", "FK_Module_DataManager", "DataManager", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(DataManager), "Module", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType([Module]), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class dashbaordDBEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new dashbaordDBEntities object using the connection string found in the 'dashbaordDBEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=dashbaordDBEntities", "dashbaordDBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new dashbaordDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "dashbaordDBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new dashbaordDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "dashbaordDBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property DataManagers() As ObjectSet(Of DataManager)
        Get
            If (_DataManagers Is Nothing) Then
                _DataManagers = MyBase.CreateObjectSet(Of DataManager)("DataManagers")
            End If
            Return _DataManagers
        End Get
    End Property

    Private _DataManagers As ObjectSet(Of DataManager)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Modules() As ObjectSet(Of [Module])
        Get
            If (_Modules Is Nothing) Then
                _Modules = MyBase.CreateObjectSet(Of [Module])("Modules")
            End If
            Return _Modules
        End Get
    End Property

    Private _Modules As ObjectSet(Of [Module])

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ReportLogStatus() As ObjectSet(Of ReportLogStatu)
        Get
            If (_ReportLogStatus Is Nothing) Then
                _ReportLogStatus = MyBase.CreateObjectSet(Of ReportLogStatu)("ReportLogStatus")
            End If
            Return _ReportLogStatus
        End Get
    End Property

    Private _ReportLogStatus As ObjectSet(Of ReportLogStatu)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Reports() As ObjectSet(Of Report)
        Get
            If (_Reports Is Nothing) Then
                _Reports = MyBase.CreateObjectSet(Of Report)("Reports")
            End If
            Return _Reports
        End Get
    End Property

    Private _Reports As ObjectSet(Of Report)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ReportStatus() As ObjectSet(Of ReportStatu)
        Get
            If (_ReportStatus Is Nothing) Then
                _ReportStatus = MyBase.CreateObjectSet(Of ReportStatu)("ReportStatus")
            End If
            Return _ReportStatus
        End Get
    End Property

    Private _ReportStatus As ObjectSet(Of ReportStatu)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property sysdiagrams() As ObjectSet(Of sysdiagram)
        Get
            If (_sysdiagrams Is Nothing) Then
                _sysdiagrams = MyBase.CreateObjectSet(Of sysdiagram)("sysdiagrams")
            End If
            Return _sysdiagrams
        End Get
    End Property

    Private _sysdiagrams As ObjectSet(Of sysdiagram)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the DataManagers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToDataManagers(ByVal dataManager As DataManager)
        MyBase.AddObject("DataManagers", dataManager)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Modules EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToModules(ByVal [module] As [Module])
        MyBase.AddObject("Modules", [module])
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ReportLogStatus EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToReportLogStatus(ByVal reportLogStatu As ReportLogStatu)
        MyBase.AddObject("ReportLogStatus", reportLogStatu)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Reports EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToReports(ByVal report As Report)
        MyBase.AddObject("Reports", report)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ReportStatus EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToReportStatus(ByVal reportStatu As ReportStatu)
        MyBase.AddObject("ReportStatus", reportStatu)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTosysdiagrams(ByVal sysdiagram As sysdiagram)
        MyBase.AddObject("sysdiagrams", sysdiagram)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dashbaordDBModel", Name:="DataManager")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class DataManager
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new DataManager object.
    ''' </summary>
    ''' <param name="dMCardID">Initial value of the DMCardID property.</param>
    Public Shared Function CreateDataManager(dMCardID As Global.System.String) As DataManager
        Dim dataManager as DataManager = New DataManager
        dataManager.DMCardID = dMCardID
        Return dataManager
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DMCardID() As Global.System.String
        Get
            Return _DMCardID
        End Get
        Set
            If (_DMCardID <> Value) Then
                OnDMCardIDChanging(value)
                ReportPropertyChanging("DMCardID")
                _DMCardID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("DMCardID")
                OnDMCardIDChanged()
            End If
        End Set
    End Property

    Private _DMCardID As Global.System.String
    Private Partial Sub OnDMCardIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDMCardIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DMFirstName() As Global.System.String
        Get
            Return _DMFirstName
        End Get
        Set
            OnDMFirstNameChanging(value)
            ReportPropertyChanging("DMFirstName")
            _DMFirstName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DMFirstName")
            OnDMFirstNameChanged()
        End Set
    End Property

    Private _DMFirstName As Global.System.String
    Private Partial Sub OnDMFirstNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDMFirstNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DMLastName() As Global.System.String
        Get
            Return _DMLastName
        End Get
        Set
            OnDMLastNameChanging(value)
            ReportPropertyChanging("DMLastName")
            _DMLastName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DMLastName")
            OnDMLastNameChanged()
        End Set
    End Property

    Private _DMLastName As Global.System.String
    Private Partial Sub OnDMLastNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDMLastNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CreatedAt() As Nullable(Of Global.System.DateTime)
        Get
            Return _CreatedAt
        End Get
        Set
            OnCreatedAtChanging(value)
            ReportPropertyChanging("CreatedAt")
            _CreatedAt = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CreatedAt")
            OnCreatedAtChanged()
        End Set
    End Property

    Private _CreatedAt As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnCreatedAtChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnCreatedAtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CreatedBy() As Global.System.String
        Get
            Return _CreatedBy
        End Get
        Set
            OnCreatedByChanging(value)
            ReportPropertyChanging("CreatedBy")
            _CreatedBy = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CreatedBy")
            OnCreatedByChanged()
        End Set
    End Property

    Private _CreatedBy As Global.System.String
    Private Partial Sub OnCreatedByChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCreatedByChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UpdatedAt() As Nullable(Of Global.System.DateTime)
        Get
            Return _UpdatedAt
        End Get
        Set
            OnUpdatedAtChanging(value)
            ReportPropertyChanging("UpdatedAt")
            _UpdatedAt = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UpdatedAt")
            OnUpdatedAtChanged()
        End Set
    End Property

    Private _UpdatedAt As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnUpdatedAtChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnUpdatedAtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UpdateBy() As Global.System.String
        Get
            Return _UpdateBy
        End Get
        Set
            OnUpdateByChanging(value)
            ReportPropertyChanging("UpdateBy")
            _UpdateBy = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("UpdateBy")
            OnUpdateByChanged()
        End Set
    End Property

    Private _UpdateBy As Global.System.String
    Private Partial Sub OnUpdateByChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUpdateByChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VoidedAt() As Nullable(Of Global.System.DateTime)
        Get
            Return _VoidedAt
        End Get
        Set
            OnVoidedAtChanging(value)
            ReportPropertyChanging("VoidedAt")
            _VoidedAt = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("VoidedAt")
            OnVoidedAtChanged()
        End Set
    End Property

    Private _VoidedAt As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnVoidedAtChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnVoidedAtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VoidedBy() As Global.System.String
        Get
            Return _VoidedBy
        End Get
        Set
            OnVoidedByChanging(value)
            ReportPropertyChanging("VoidedBy")
            _VoidedBy = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("VoidedBy")
            OnVoidedByChanged()
        End Set
    End Property

    Private _VoidedBy As Global.System.String
    Private Partial Sub OnVoidedByChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVoidedByChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Voided() As Nullable(Of Global.System.Boolean)
        Get
            Return _Voided
        End Get
        Set
            OnVoidedChanging(value)
            ReportPropertyChanging("Voided")
            _Voided = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Voided")
            OnVoidedChanged()
        End Set
    End Property

    Private _Voided As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnVoidedChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnVoidedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Active() As Nullable(Of Global.System.Boolean)
        Get
            Return _Active
        End Get
        Set
            OnActiveChanging(value)
            ReportPropertyChanging("Active")
            _Active = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Active")
            OnActiveChanged()
        End Set
    End Property

    Private _Active As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnActiveChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnActiveChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dashbaordDBModel", "FK_Module_DataManager", "Module")>
     Public Property Modules() As EntityCollection(Of [Module])
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of [Module])("dashbaordDBModel.FK_Module_DataManager", "Module")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of [Module])("dashbaordDBModel.FK_Module_DataManager", "Module", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dashbaordDBModel", Name:="Module")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class [Module]
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Module object.
    ''' </summary>
    ''' <param name="moduleID">Initial value of the ModuleID property.</param>
    Public Shared Function CreateModule(moduleID As Global.System.Int32) As [Module]
        Dim [module] as [Module] = New [Module]
        [module].ModuleID = moduleID
        Return [module]
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ModuleID() As Global.System.Int32
        Get
            Return _ModuleID
        End Get
        Set
            If (_ModuleID <> Value) Then
                OnModuleIDChanging(value)
                ReportPropertyChanging("ModuleID")
                _ModuleID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ModuleID")
                OnModuleIDChanged()
            End If
        End Set
    End Property

    Private _ModuleID As Global.System.Int32
    Private Partial Sub OnModuleIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnModuleIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ModuleName() As Global.System.String
        Get
            Return _ModuleName
        End Get
        Set
            OnModuleNameChanging(value)
            ReportPropertyChanging("ModuleName")
            _ModuleName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ModuleName")
            OnModuleNameChanged()
        End Set
    End Property

    Private _ModuleName As Global.System.String
    Private Partial Sub OnModuleNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnModuleNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ModuleDesc() As Global.System.String
        Get
            Return _ModuleDesc
        End Get
        Set
            OnModuleDescChanging(value)
            ReportPropertyChanging("ModuleDesc")
            _ModuleDesc = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ModuleDesc")
            OnModuleDescChanged()
        End Set
    End Property

    Private _ModuleDesc As Global.System.String
    Private Partial Sub OnModuleDescChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnModuleDescChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CreatedAt() As Nullable(Of Global.System.DateTime)
        Get
            Return _CreatedAt
        End Get
        Set
            OnCreatedAtChanging(value)
            ReportPropertyChanging("CreatedAt")
            _CreatedAt = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CreatedAt")
            OnCreatedAtChanged()
        End Set
    End Property

    Private _CreatedAt As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnCreatedAtChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnCreatedAtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CreatedBy() As Global.System.String
        Get
            Return _CreatedBy
        End Get
        Set
            OnCreatedByChanging(value)
            ReportPropertyChanging("CreatedBy")
            _CreatedBy = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CreatedBy")
            OnCreatedByChanged()
        End Set
    End Property

    Private _CreatedBy As Global.System.String
    Private Partial Sub OnCreatedByChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCreatedByChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UpdatedAt() As Nullable(Of Global.System.DateTime)
        Get
            Return _UpdatedAt
        End Get
        Set
            OnUpdatedAtChanging(value)
            ReportPropertyChanging("UpdatedAt")
            _UpdatedAt = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UpdatedAt")
            OnUpdatedAtChanged()
        End Set
    End Property

    Private _UpdatedAt As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnUpdatedAtChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnUpdatedAtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UpdateBy() As Global.System.String
        Get
            Return _UpdateBy
        End Get
        Set
            OnUpdateByChanging(value)
            ReportPropertyChanging("UpdateBy")
            _UpdateBy = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("UpdateBy")
            OnUpdateByChanged()
        End Set
    End Property

    Private _UpdateBy As Global.System.String
    Private Partial Sub OnUpdateByChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUpdateByChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VoidedAt() As Nullable(Of Global.System.DateTime)
        Get
            Return _VoidedAt
        End Get
        Set
            OnVoidedAtChanging(value)
            ReportPropertyChanging("VoidedAt")
            _VoidedAt = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("VoidedAt")
            OnVoidedAtChanged()
        End Set
    End Property

    Private _VoidedAt As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnVoidedAtChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnVoidedAtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VoidedBy() As Global.System.String
        Get
            Return _VoidedBy
        End Get
        Set
            OnVoidedByChanging(value)
            ReportPropertyChanging("VoidedBy")
            _VoidedBy = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("VoidedBy")
            OnVoidedByChanged()
        End Set
    End Property

    Private _VoidedBy As Global.System.String
    Private Partial Sub OnVoidedByChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVoidedByChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DMCardID() As Global.System.String
        Get
            Return _DMCardID
        End Get
        Set
            OnDMCardIDChanging(value)
            ReportPropertyChanging("DMCardID")
            _DMCardID = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DMCardID")
            OnDMCardIDChanged()
        End Set
    End Property

    Private _DMCardID As Global.System.String
    Private Partial Sub OnDMCardIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDMCardIDChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dashbaordDBModel", "FK_Reports_Module1", "Reports")>
     Public Property Reports() As EntityCollection(Of Report)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Report)("dashbaordDBModel.FK_Reports_Module1", "Reports")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Report)("dashbaordDBModel.FK_Reports_Module1", "Reports", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dashbaordDBModel", "FK_Module_DataManager", "DataManager")>
    Public Property DataManager() As DataManager
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DataManager)("dashbaordDBModel.FK_Module_DataManager", "DataManager").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DataManager)("dashbaordDBModel.FK_Module_DataManager", "DataManager").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property DataManagerReference() As EntityReference(Of DataManager)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DataManager)("dashbaordDBModel.FK_Module_DataManager", "DataManager")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of DataManager)("dashbaordDBModel.FK_Module_DataManager", "DataManager", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dashbaordDBModel", Name:="Report")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Report
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Report object.
    ''' </summary>
    ''' <param name="reportID">Initial value of the ReportID property.</param>
    ''' <param name="reportDesc">Initial value of the ReportDesc property.</param>
    ''' <param name="serverName">Initial value of the ServerName property.</param>
    ''' <param name="serverPath">Initial value of the ServerPath property.</param>
    Public Shared Function CreateReport(reportID As Global.System.Int32, reportDesc As Global.System.String, serverName As Global.System.String, serverPath As Global.System.String) As Report
        Dim report as Report = New Report
        report.ReportID = reportID
        report.ReportDesc = reportDesc
        report.ServerName = serverName
        report.ServerPath = serverPath
        Return report
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ReportID() As Global.System.Int32
        Get
            Return _ReportID
        End Get
        Set
            If (_ReportID <> Value) Then
                OnReportIDChanging(value)
                ReportPropertyChanging("ReportID")
                _ReportID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ReportID")
                OnReportIDChanged()
            End If
        End Set
    End Property

    Private _ReportID As Global.System.Int32
    Private Partial Sub OnReportIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnReportIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ModuleID() As Nullable(Of Global.System.Int32)
        Get
            Return _ModuleID
        End Get
        Set
            OnModuleIDChanging(value)
            ReportPropertyChanging("ModuleID")
            _ModuleID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ModuleID")
            OnModuleIDChanged()
        End Set
    End Property

    Private _ModuleID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnModuleIDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnModuleIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ReportName() As Global.System.String
        Get
            Return _ReportName
        End Get
        Set
            OnReportNameChanging(value)
            ReportPropertyChanging("ReportName")
            _ReportName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ReportName")
            OnReportNameChanged()
        End Set
    End Property

    Private _ReportName As Global.System.String
    Private Partial Sub OnReportNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnReportNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ReportDesc() As Global.System.String
        Get
            Return _ReportDesc
        End Get
        Set
            OnReportDescChanging(value)
            ReportPropertyChanging("ReportDesc")
            _ReportDesc = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ReportDesc")
            OnReportDescChanged()
        End Set
    End Property

    Private _ReportDesc As Global.System.String
    Private Partial Sub OnReportDescChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnReportDescChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ServerName() As Global.System.String
        Get
            Return _ServerName
        End Get
        Set
            OnServerNameChanging(value)
            ReportPropertyChanging("ServerName")
            _ServerName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ServerName")
            OnServerNameChanged()
        End Set
    End Property

    Private _ServerName As Global.System.String
    Private Partial Sub OnServerNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnServerNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ServerPath() As Global.System.String
        Get
            Return _ServerPath
        End Get
        Set
            OnServerPathChanging(value)
            ReportPropertyChanging("ServerPath")
            _ServerPath = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ServerPath")
            OnServerPathChanged()
        End Set
    End Property

    Private _ServerPath As Global.System.String
    Private Partial Sub OnServerPathChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnServerPathChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FolderPath() As Global.System.String
        Get
            Return _FolderPath
        End Get
        Set
            OnFolderPathChanging(value)
            ReportPropertyChanging("FolderPath")
            _FolderPath = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("FolderPath")
            OnFolderPathChanged()
        End Set
    End Property

    Private _FolderPath As Global.System.String
    Private Partial Sub OnFolderPathChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFolderPathChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ReportFileName() As Global.System.String
        Get
            Return _ReportFileName
        End Get
        Set
            OnReportFileNameChanging(value)
            ReportPropertyChanging("ReportFileName")
            _ReportFileName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ReportFileName")
            OnReportFileNameChanged()
        End Set
    End Property

    Private _ReportFileName As Global.System.String
    Private Partial Sub OnReportFileNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnReportFileNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CreatedAt() As Nullable(Of Global.System.DateTime)
        Get
            Return _CreatedAt
        End Get
        Set
            OnCreatedAtChanging(value)
            ReportPropertyChanging("CreatedAt")
            _CreatedAt = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CreatedAt")
            OnCreatedAtChanged()
        End Set
    End Property

    Private _CreatedAt As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnCreatedAtChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnCreatedAtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CreatedBy() As Global.System.String
        Get
            Return _CreatedBy
        End Get
        Set
            OnCreatedByChanging(value)
            ReportPropertyChanging("CreatedBy")
            _CreatedBy = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CreatedBy")
            OnCreatedByChanged()
        End Set
    End Property

    Private _CreatedBy As Global.System.String
    Private Partial Sub OnCreatedByChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCreatedByChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UpdatedAt() As Nullable(Of Global.System.DateTime)
        Get
            Return _UpdatedAt
        End Get
        Set
            OnUpdatedAtChanging(value)
            ReportPropertyChanging("UpdatedAt")
            _UpdatedAt = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UpdatedAt")
            OnUpdatedAtChanged()
        End Set
    End Property

    Private _UpdatedAt As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnUpdatedAtChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnUpdatedAtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UpdateBy() As Global.System.String
        Get
            Return _UpdateBy
        End Get
        Set
            OnUpdateByChanging(value)
            ReportPropertyChanging("UpdateBy")
            _UpdateBy = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("UpdateBy")
            OnUpdateByChanged()
        End Set
    End Property

    Private _UpdateBy As Global.System.String
    Private Partial Sub OnUpdateByChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUpdateByChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VoidedAt() As Nullable(Of Global.System.DateTime)
        Get
            Return _VoidedAt
        End Get
        Set
            OnVoidedAtChanging(value)
            ReportPropertyChanging("VoidedAt")
            _VoidedAt = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("VoidedAt")
            OnVoidedAtChanged()
        End Set
    End Property

    Private _VoidedAt As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnVoidedAtChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnVoidedAtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VoidedBy() As Global.System.String
        Get
            Return _VoidedBy
        End Get
        Set
            OnVoidedByChanging(value)
            ReportPropertyChanging("VoidedBy")
            _VoidedBy = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("VoidedBy")
            OnVoidedByChanged()
        End Set
    End Property

    Private _VoidedBy As Global.System.String
    Private Partial Sub OnVoidedByChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVoidedByChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PublishedBy() As Global.System.String
        Get
            Return _PublishedBy
        End Get
        Set
            OnPublishedByChanging(value)
            ReportPropertyChanging("PublishedBy")
            _PublishedBy = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("PublishedBy")
            OnPublishedByChanged()
        End Set
    End Property

    Private _PublishedBy As Global.System.String
    Private Partial Sub OnPublishedByChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPublishedByChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CurrentStatus() As Nullable(Of Global.System.Int32)
        Get
            Return _CurrentStatus
        End Get
        Set
            OnCurrentStatusChanging(value)
            ReportPropertyChanging("CurrentStatus")
            _CurrentStatus = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CurrentStatus")
            OnCurrentStatusChanged()
        End Set
    End Property

    Private _CurrentStatus As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCurrentStatusChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCurrentStatusChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dashbaordDBModel", "FK_Reports_Module1", "Module")>
    Public Property [Module]() As [Module]
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of [Module])("dashbaordDBModel.FK_Reports_Module1", "Module").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of [Module])("dashbaordDBModel.FK_Reports_Module1", "Module").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ModuleReference() As EntityReference(Of [Module])
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of [Module])("dashbaordDBModel.FK_Reports_Module1", "Module")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of [Module])("dashbaordDBModel.FK_Reports_Module1", "Module", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dashbaordDBModel", "FK_ReportLogStatus_Reports", "ReportLogStatus")>
     Public Property ReportLogStatus() As EntityCollection(Of ReportLogStatu)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ReportLogStatu)("dashbaordDBModel.FK_ReportLogStatus_Reports", "ReportLogStatus")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ReportLogStatu)("dashbaordDBModel.FK_ReportLogStatus_Reports", "ReportLogStatus", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dashbaordDBModel", Name:="ReportLogStatu")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ReportLogStatu
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ReportLogStatu object.
    ''' </summary>
    ''' <param name="reportID">Initial value of the ReportID property.</param>
    ''' <param name="statusID">Initial value of the StatusID property.</param>
    Public Shared Function CreateReportLogStatu(reportID As Global.System.Int32, statusID As Global.System.Int32) As ReportLogStatu
        Dim reportLogStatu as ReportLogStatu = New ReportLogStatu
        reportLogStatu.ReportID = reportID
        reportLogStatu.StatusID = statusID
        Return reportLogStatu
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ReportID() As Global.System.Int32
        Get
            Return _ReportID
        End Get
        Set
            If (_ReportID <> Value) Then
                OnReportIDChanging(value)
                ReportPropertyChanging("ReportID")
                _ReportID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ReportID")
                OnReportIDChanged()
            End If
        End Set
    End Property

    Private _ReportID As Global.System.Int32
    Private Partial Sub OnReportIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnReportIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StatusID() As Global.System.Int32
        Get
            Return _StatusID
        End Get
        Set
            If (_StatusID <> Value) Then
                OnStatusIDChanging(value)
                ReportPropertyChanging("StatusID")
                _StatusID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("StatusID")
                OnStatusIDChanged()
            End If
        End Set
    End Property

    Private _StatusID As Global.System.Int32
    Private Partial Sub OnStatusIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnStatusIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Comment() As Global.System.String
        Get
            Return _Comment
        End Get
        Set
            OnCommentChanging(value)
            ReportPropertyChanging("Comment")
            _Comment = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Comment")
            OnCommentChanged()
        End Set
    End Property

    Private _Comment As Global.System.String
    Private Partial Sub OnCommentChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCommentChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CreatedAt() As Nullable(Of Global.System.DateTime)
        Get
            Return _CreatedAt
        End Get
        Set
            OnCreatedAtChanging(value)
            ReportPropertyChanging("CreatedAt")
            _CreatedAt = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CreatedAt")
            OnCreatedAtChanged()
        End Set
    End Property

    Private _CreatedAt As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnCreatedAtChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnCreatedAtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CreatedBy() As Global.System.String
        Get
            Return _CreatedBy
        End Get
        Set
            OnCreatedByChanging(value)
            ReportPropertyChanging("CreatedBy")
            _CreatedBy = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CreatedBy")
            OnCreatedByChanged()
        End Set
    End Property

    Private _CreatedBy As Global.System.String
    Private Partial Sub OnCreatedByChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCreatedByChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UpdatedAt() As Nullable(Of Global.System.DateTime)
        Get
            Return _UpdatedAt
        End Get
        Set
            OnUpdatedAtChanging(value)
            ReportPropertyChanging("UpdatedAt")
            _UpdatedAt = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UpdatedAt")
            OnUpdatedAtChanged()
        End Set
    End Property

    Private _UpdatedAt As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnUpdatedAtChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnUpdatedAtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UpdateBy() As Global.System.String
        Get
            Return _UpdateBy
        End Get
        Set
            OnUpdateByChanging(value)
            ReportPropertyChanging("UpdateBy")
            _UpdateBy = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("UpdateBy")
            OnUpdateByChanged()
        End Set
    End Property

    Private _UpdateBy As Global.System.String
    Private Partial Sub OnUpdateByChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUpdateByChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VoidedAt() As Nullable(Of Global.System.DateTime)
        Get
            Return _VoidedAt
        End Get
        Set
            OnVoidedAtChanging(value)
            ReportPropertyChanging("VoidedAt")
            _VoidedAt = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("VoidedAt")
            OnVoidedAtChanged()
        End Set
    End Property

    Private _VoidedAt As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnVoidedAtChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnVoidedAtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VoidedBy() As Global.System.String
        Get
            Return _VoidedBy
        End Get
        Set
            OnVoidedByChanging(value)
            ReportPropertyChanging("VoidedBy")
            _VoidedBy = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("VoidedBy")
            OnVoidedByChanged()
        End Set
    End Property

    Private _VoidedBy As Global.System.String
    Private Partial Sub OnVoidedByChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVoidedByChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Voided() As Nullable(Of Global.System.Boolean)
        Get
            Return _Voided
        End Get
        Set
            OnVoidedChanging(value)
            ReportPropertyChanging("Voided")
            _Voided = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Voided")
            OnVoidedChanged()
        End Set
    End Property

    Private _Voided As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnVoidedChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnVoidedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Active() As Nullable(Of Global.System.Boolean)
        Get
            Return _Active
        End Get
        Set
            OnActiveChanging(value)
            ReportPropertyChanging("Active")
            _Active = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Active")
            OnActiveChanged()
        End Set
    End Property

    Private _Active As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnActiveChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnActiveChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dashbaordDBModel", "FK_ReportLogStatus_Reports", "Reports")>
    Public Property Report() As Report
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Report)("dashbaordDBModel.FK_ReportLogStatus_Reports", "Reports").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Report)("dashbaordDBModel.FK_ReportLogStatus_Reports", "Reports").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ReportReference() As EntityReference(Of Report)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Report)("dashbaordDBModel.FK_ReportLogStatus_Reports", "Reports")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Report)("dashbaordDBModel.FK_ReportLogStatus_Reports", "Reports", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dashbaordDBModel", "FK_ReportLogStatus_ReportStatus", "ReportStatus")>
    Public Property ReportStatu() As ReportStatu
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ReportStatu)("dashbaordDBModel.FK_ReportLogStatus_ReportStatus", "ReportStatus").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ReportStatu)("dashbaordDBModel.FK_ReportLogStatus_ReportStatus", "ReportStatus").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ReportStatuReference() As EntityReference(Of ReportStatu)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ReportStatu)("dashbaordDBModel.FK_ReportLogStatus_ReportStatus", "ReportStatus")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of ReportStatu)("dashbaordDBModel.FK_ReportLogStatus_ReportStatus", "ReportStatus", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dashbaordDBModel", Name:="ReportStatu")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ReportStatu
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ReportStatu object.
    ''' </summary>
    ''' <param name="statusID">Initial value of the StatusID property.</param>
    Public Shared Function CreateReportStatu(statusID As Global.System.Int32) As ReportStatu
        Dim reportStatu as ReportStatu = New ReportStatu
        reportStatu.StatusID = statusID
        Return reportStatu
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StatusID() As Global.System.Int32
        Get
            Return _StatusID
        End Get
        Set
            If (_StatusID <> Value) Then
                OnStatusIDChanging(value)
                ReportPropertyChanging("StatusID")
                _StatusID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("StatusID")
                OnStatusIDChanged()
            End If
        End Set
    End Property

    Private _StatusID As Global.System.Int32
    Private Partial Sub OnStatusIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnStatusIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property StatusName() As Global.System.String
        Get
            Return _StatusName
        End Get
        Set
            OnStatusNameChanging(value)
            ReportPropertyChanging("StatusName")
            _StatusName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("StatusName")
            OnStatusNameChanged()
        End Set
    End Property

    Private _StatusName As Global.System.String
    Private Partial Sub OnStatusNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStatusNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property StatusDesc() As Global.System.String
        Get
            Return _StatusDesc
        End Get
        Set
            OnStatusDescChanging(value)
            ReportPropertyChanging("StatusDesc")
            _StatusDesc = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("StatusDesc")
            OnStatusDescChanged()
        End Set
    End Property

    Private _StatusDesc As Global.System.String
    Private Partial Sub OnStatusDescChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStatusDescChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dashbaordDBModel", "FK_ReportLogStatus_ReportStatus", "ReportLogStatus")>
     Public Property ReportLogStatus() As EntityCollection(Of ReportLogStatu)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ReportLogStatu)("dashbaordDBModel.FK_ReportLogStatus_ReportStatus", "ReportLogStatus")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ReportLogStatu)("dashbaordDBModel.FK_ReportLogStatus_ReportStatus", "ReportLogStatus", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dashbaordDBModel", Name:="sysdiagram")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class sysdiagram
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new sysdiagram object.
    ''' </summary>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="principal_id">Initial value of the principal_id property.</param>
    ''' <param name="diagram_id">Initial value of the diagram_id property.</param>
    Public Shared Function Createsysdiagram(name As Global.System.String, principal_id As Global.System.Int32, diagram_id As Global.System.Int32) As sysdiagram
        Dim sysdiagram as sysdiagram = New sysdiagram
        sysdiagram.name = name
        sysdiagram.principal_id = principal_id
        sysdiagram.diagram_id = diagram_id
        Return sysdiagram
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property principal_id() As Global.System.Int32
        Get
            Return _principal_id
        End Get
        Set
            Onprincipal_idChanging(value)
            ReportPropertyChanging("principal_id")
            _principal_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("principal_id")
            Onprincipal_idChanged()
        End Set
    End Property

    Private _principal_id As Global.System.Int32
    Private Partial Sub Onprincipal_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onprincipal_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property diagram_id() As Global.System.Int32
        Get
            Return _diagram_id
        End Get
        Set
            If (_diagram_id <> Value) Then
                Ondiagram_idChanging(value)
                ReportPropertyChanging("diagram_id")
                _diagram_id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("diagram_id")
                Ondiagram_idChanged()
            End If
        End Set
    End Property

    Private _diagram_id As Global.System.Int32
    Private Partial Sub Ondiagram_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ondiagram_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property version() As Nullable(Of Global.System.Int32)
        Get
            Return _version
        End Get
        Set
            OnversionChanging(value)
            ReportPropertyChanging("version")
            _version = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("version")
            OnversionChanged()
        End Set
    End Property

    Private _version As Nullable(Of Global.System.Int32)
    Private Partial Sub OnversionChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnversionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property definition() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_definition)
        End Get
        Set
            OndefinitionChanging(value)
            ReportPropertyChanging("definition")
            _definition = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("definition")
            OndefinitionChanged()
        End Set
    End Property

    Private _definition As Global.System.Byte()
    Private Partial Sub OndefinitionChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OndefinitionChanged()
    End Sub

    #End Region

End Class

#End Region


